/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: do not edit it. Instead, edit the BAML
// files and re-generate this code.
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code
import { BamlRuntime, FunctionResult, BamlCtxManager, BamlStream, Image, ClientRegistry, toBamlError, Audio } from "@boundaryml/baml"
import { Checked, Check, RecursivePartialNull as MovedRecursivePartialNull } from "./types"
import type { partial_types } from "./partial_types"
import {ConfidenceLevel, DuplicateCheckResult, ExtractedDate, ExtractedTask, ProjectSuggestion, TagSuggestion, TaskExtractionResult} from "./types"
import * as types from "./types"
import type TypeBuilder from "./type_builder"
import { DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_CTX, DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME } from "./globals"

/**
 * @deprecated Use RecursivePartialNull from 'baml_client/types' instead.
 */
export type RecursivePartialNull<T> = MovedRecursivePartialNull<T>

export class BamlAsyncClient {
  private runtime: BamlRuntime
  private ctx_manager: BamlCtxManager
  private stream_client: BamlStreamClient

  constructor(runtime: BamlRuntime, ctx_manager: BamlCtxManager) {
    this.runtime = runtime
    this.ctx_manager = ctx_manager
    this.stream_client = new BamlStreamClient(runtime, ctx_manager)
  }

  get stream() {
    return this.stream_client
  }

  
  async CheckDuplicate(
      newTaskTitle: string,newTaskNote?: string | null,existingTasks: string[],
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry }
  ): Promise<DuplicateCheckResult> {
    try {
      const raw = await this.runtime.callFunction(
        "CheckDuplicate",
        {
          "newTaskTitle": newTaskTitle,"newTaskNote": newTaskNote?? null,"existingTasks": existingTasks
        },
        this.ctx_manager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
      )
      return raw.parsed(false) as DuplicateCheckResult
    } catch (error: any) {
      throw toBamlError(error);
    }
  }
  
  async ExtractTasks(
      input: string,currentDate: string,existingProjects: string[],existingTags: string[],
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry }
  ): Promise<TaskExtractionResult> {
    try {
      const raw = await this.runtime.callFunction(
        "ExtractTasks",
        {
          "input": input,"currentDate": currentDate,"existingProjects": existingProjects,"existingTags": existingTags
        },
        this.ctx_manager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
      )
      return raw.parsed(false) as TaskExtractionResult
    } catch (error: any) {
      throw toBamlError(error);
    }
  }
  
}

class BamlStreamClient {
  constructor(private runtime: BamlRuntime, private ctx_manager: BamlCtxManager) {}

  
  CheckDuplicate(
      newTaskTitle: string,newTaskNote?: string | null,existingTasks: string[],
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry }
  ): BamlStream<partial_types.DuplicateCheckResult, DuplicateCheckResult> {
    try {
      const raw = this.runtime.streamFunction(
        "CheckDuplicate",
        {
          "newTaskTitle": newTaskTitle,"newTaskNote": newTaskNote ?? null,"existingTasks": existingTasks
        },
        undefined,
        this.ctx_manager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
      )
      return new BamlStream<partial_types.DuplicateCheckResult, DuplicateCheckResult>(
        raw,
        (a): partial_types.DuplicateCheckResult => a,
        (a): DuplicateCheckResult => a,
        this.ctx_manager.cloneContext(),
      )
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  ExtractTasks(
      input: string,currentDate: string,existingProjects: string[],existingTags: string[],
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry }
  ): BamlStream<partial_types.TaskExtractionResult, TaskExtractionResult> {
    try {
      const raw = this.runtime.streamFunction(
        "ExtractTasks",
        {
          "input": input,"currentDate": currentDate,"existingProjects": existingProjects,"existingTags": existingTags
        },
        undefined,
        this.ctx_manager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
      )
      return new BamlStream<partial_types.TaskExtractionResult, TaskExtractionResult>(
        raw,
        (a): partial_types.TaskExtractionResult => a,
        (a): TaskExtractionResult => a,
        this.ctx_manager.cloneContext(),
      )
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
}

export const b = new BamlAsyncClient(DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME, DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_CTX)