/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: do not edit it. Instead, edit the BAML
// files and re-generate this code.
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code
import type { Image, Audio } from "@boundaryml/baml"
import type { Checked, Check } from "./types"
import type {  ConfidenceLevel,  DuplicateCheckResult,  ExtractedDate,  ExtractedTask,  ProjectSuggestion,  TagSuggestion,  TaskExtractionResult } from "./types"
import type * as types from "./types"

/******************************************************************************
*
*  These types are used for streaming, for when an instance of a type
*  is still being built up and any of its fields is not yet fully available.
*
******************************************************************************/

export interface StreamState<T> {
    value: T
    state: "Pending" | "Incomplete" | "Complete"
}

export namespace partial_types {
    
    export interface DuplicateCheckResult {
        isDuplicate?: (boolean | null)
        matchType: ((string | null) | null)
        existingTaskTitle: ((string | null) | null)
        confidence?: (ConfidenceLevel | null)
        suggestion: ((string | null) | null)
    }
    
    export interface ExtractedDate {
        value?: (string | null)
        timeSpecified?: (boolean | null)
        confidence?: (ConfidenceLevel | null)
        originalText?: (string | null)
    }
    
    export interface ExtractedTask {
        title?: (string | null)
        note: ((string | null) | null)
        dueDate: ((partial_types.ExtractedDate | null) | null)
        deferDate: ((partial_types.ExtractedDate | null) | null)
        estimatedMinutes: ((number | null) | null)
        isWaitingFor?: (boolean | null)
        waitingForPerson: ((string | null) | null)
        suggestedProjects?: (partial_types.ProjectSuggestion | null)[]
        suggestedTags?: (partial_types.TagSuggestion | null)[]
        isUrgent?: (boolean | null)
    }
    
    export interface ProjectSuggestion {
        name?: (string | null)
        confidence?: (ConfidenceLevel | null)
        reason: ((string | null) | null)
    }
    
    export interface TagSuggestion {
        name?: (string | null)
        confidence?: (ConfidenceLevel | null)
        reason: ((string | null) | null)
    }
    
    export interface TaskExtractionResult {
        tasks?: (partial_types.ExtractedTask | null)[]
        needsClarification?: (boolean | null)
        clarificationQuestion: ((string | null) | null)
        alternativeInterpretations: ((string | null)[] | null)
    }
    
}