/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: do not edit it. Instead, edit the BAML
// files and re-generate this code.
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code
import type { Image, Audio } from "@boundaryml/baml"

/**
 * Recursively partial type that can be null.
 *
 * @deprecated Use types from the `partial_types` namespace instead, which provides type-safe partial implementations
 * @template T The type to make recursively partial.
 */
export type RecursivePartialNull<T> = T extends object
    ? { [P in keyof T]?: RecursivePartialNull<T[P]> }
    : T | null;

export interface Checked<T,CheckName extends string = string> {
    value: T,
    checks: Record<CheckName, Check>,
}

export interface Check {
    name: string,
    expr: string
    status: "succeeded" | "failed"
}

export function all_succeeded<CheckName extends string>(checks: Record<CheckName, Check>): boolean {
    return get_checks(checks).every(check => check.status === "succeeded")
}

export function get_checks<CheckName extends string>(checks: Record<CheckName, Check>): Check[] {
    return Object.values(checks)
}
export enum ConfidenceLevel {
  HIGH = "HIGH",
  MEDIUM = "MEDIUM",
  LOW = "LOW",
}

export interface DuplicateCheckResult {
  isDuplicate: boolean
  matchType?: string | null
  existingTaskTitle?: string | null
  confidence: ConfidenceLevel
  suggestion?: string | null
  
}

export interface ExtractedDate {
  value: string
  timeSpecified: boolean
  confidence: ConfidenceLevel
  originalText: string
  
}

export interface ExtractedTask {
  title: string
  note?: string | null
  dueDate?: ExtractedDate | null
  deferDate?: ExtractedDate | null
  estimatedMinutes?: number | null
  isWaitingFor: boolean
  waitingForPerson?: string | null
  suggestedProjects: ProjectSuggestion[]
  suggestedTags: TagSuggestion[]
  isUrgent: boolean
  
}

export interface ProjectSuggestion {
  name: string
  confidence: ConfidenceLevel
  reason?: string | null
  
}

export interface TagSuggestion {
  name: string
  confidence: ConfidenceLevel
  reason?: string | null
  
}

export interface TaskExtractionResult {
  tasks: ExtractedTask[]
  needsClarification: boolean
  clarificationQuestion?: string | null
  alternativeInterpretations?: string[] | null
  
}
